export type AnalyticInfo = {
    count: number;
    orders: number;
    sum_orders: number;
    sales: number;
    sum_sales: number;
    sum: number;
    profit: number;
    rentabelnost: any;
    stocks: number;
    skuInStock: number;
    expectedSalesForBuyoutsPercent: number;
    openCardCount: number;
    addToCartCount: number;
    addToCartPercent: number;
    cartToOrderPercent: number;
    buyoutsPercent: number;
    expectedSales: number;
    storageCost: number;
    views: number;
    clicks: number;
    salesPrimeCost: number;
    comission: number;
    tax: number;
    expences: number;
    logisticks: number;
    sppPriceTemp: number;
    primeCost: number;
    sppPrice: number;
};

export type AnalyticTableView = AnalyticInfo & {
    avgCost: number;
    cpc: number;
    cpl: number;
    cpm: number;
    cr: number;
    ctr: number;
    date: string;
    drr_orders: number;
    drr_sales: number;
    entity: string;
    isSummary: boolean;
    logisticsPercent: number;
    notes: undefined;
    obor: number;
    oborSales: number;
    orderPrice: number;
    rentPrimeCost: number;
    rentSales: number;
    romi: number;
};
