export interface ClusterDataDto {
	addToCartCurrent: number
	addToCartPercentile: number
	avgPositionCurrent: number
	cartToOrderCurrent: number
	cartToOrderPercentile: number
	clicks: number
	cluster: string
	cpc: number
	ctr: number
	cpm: number
	frequencyCurrent: number
	openCardCurrent: number
	openCardPercentile: number
	openToCartCurrent: number
	openToCartPercentile: number
	openToOrderPercent: number
	ordersCurrent: number
	ordersPercentile: number
	preset: string
	totalFrequency: number
	totalSum: number
	views: number
	visibilityCurrent: number
	weekFrequency: number
	drr: number
	cpo: number
	profitSum: number
}