export const nameOfColumns : Record<string, string>= {
	date: "Дата и время",
	orders: "Заказы",
	sumOrders: "Заказы, ₽",
	sum: "Расход, ₽'",
	views: 'Профит, ₽',
	clicks:'Клики, шт.',
	drr: 'ДРР, %',
	ctr:'CTR, %',
	cpc: 'CPC, ₽',
	cpm: 'CPM, ₽',
	cpo: "CPO, ₽",
	openCardCount: 'Всего переходов, шт.',
	addToCartCount:'Корзины, шт.',
	addToCartPercent: 'CR в корзину, %',
	cartToOrderPercent: 'CR в заказ, %',
	cr:'CR из перехода, %',
	crFromView: 'CR из показа, %',
	profit: 'Профит, ₽',
	rent: 'Рентабельность, %',
	cpl: 'CPL, ₽',
	avgPrice:  'Ср. Чек, ₽',
}